version: "3.9"
services:
  cassandra:
    build: ./internal/database
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra:/var/lib/cassandra
    networks:
      - app
    environment:
      CASSANDRA_CLUSTER_NAME: ${DB_CLUSTER_NAME}
      DB_KEYSPACE: ${DB_KEYSPACE}

  tracker:
    environment:
      DB_HOST: cassandra
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: "9042"
      DB_MIGRATE: ${DB_MIGRATE}
      DB_KEYSPACE: ${DB_KEYSPACE}
    depends_on:
      - cassandra
    build: .
    networks:
      - app

networks:
  app:

